from __future__ import annotations
from abc import ABC, abstractmethod
from models.agent import AgentRunResult
from models.artifact import ArtifactReference
from models.audit import AuditEvent
from models.control import RuntimeIdempotencyRecord
from models.intervention import HumanActionRequest, NotificationDeliveryAttempt, NotificationEvent
from models.lifecycle import ProjectLifecycleTransition
from models.observability_records import RoutingRecord, ReleaseValidationRecord
from models.operational import ProjectOperationalTransition
from models.project import Project, ProjectSpec
from models.release import Release, ReleaseTarget
from models.task import Task, WorkflowRun
from policy.contracts import ApprovalRecord, PolicyDecision


class PersistenceConflictError(RuntimeError):
    pass


class PersistenceStore(ABC):
    @abstractmethod
    def initialize(self) -> None: ...
    @abstractmethod
    def close(self) -> None: ...
    @abstractmethod
    def save_project(self, value: Project) -> None: ...
    @abstractmethod
    def save_project_with_audit(self, value: Project, audit: AuditEvent) -> None: ...
    @abstractmethod
    def get_project(self, project_id: str) -> Project | None: ...
    @abstractmethod
    def list_projects(self) -> tuple[Project, ...]: ...
    @abstractmethod
    def save_project_spec(self, value: ProjectSpec) -> None: ...
    @abstractmethod
    def get_project_spec(self, project_spec_id: str) -> ProjectSpec | None: ...
    @abstractmethod
    def list_project_specs(self, project_id: str) -> tuple[ProjectSpec, ...]: ...
    @abstractmethod
    def append_lifecycle_transition(self, value: ProjectLifecycleTransition) -> None: ...
    @abstractmethod
    def apply_lifecycle_transition(self, project: Project, value: ProjectLifecycleTransition, audit: AuditEvent | None = None) -> None: ...
    @abstractmethod
    def list_lifecycle_transitions(self, project_id: str) -> tuple[ProjectLifecycleTransition, ...]: ...
    @abstractmethod
    def append_operational_transition(self, value: ProjectOperationalTransition) -> None: ...
    @abstractmethod
    def apply_operational_transition(self, project: Project, value: ProjectOperationalTransition, audit: AuditEvent | None = None) -> None: ...
    @abstractmethod
    def list_operational_transitions(self, project_id: str) -> tuple[ProjectOperationalTransition, ...]: ...
    @abstractmethod
    def save_task(self, value: Task) -> None: ...
    @abstractmethod
    def get_task(self, task_id: str) -> Task | None: ...
    @abstractmethod
    def list_tasks(self, project_id: str) -> tuple[Task, ...]: ...
    @abstractmethod
    def save_workflow_run(self, value: WorkflowRun) -> None: ...
    @abstractmethod
    def list_workflow_runs(self, project_id: str) -> tuple[WorkflowRun, ...]: ...
    @abstractmethod
    def save_agent_run(self, value: AgentRunResult) -> None: ...
    @abstractmethod
    def list_agent_runs(self, project_id: str) -> tuple[AgentRunResult, ...]: ...
    @abstractmethod
    def save_artifact(self, value: ArtifactReference) -> None: ...
    @abstractmethod
    def list_artifacts(self, project_id: str) -> tuple[ArtifactReference, ...]: ...
    @abstractmethod
    def save_release(self, value: Release) -> None: ...
    @abstractmethod
    def get_release(self, release_id: str) -> Release | None: ...
    @abstractmethod
    def list_releases(self, project_id: str) -> tuple[Release, ...]: ...
    @abstractmethod
    def save_release_target(self, value: ReleaseTarget) -> None: ...
    @abstractmethod
    def get_release_target(self, release_target_id: str) -> ReleaseTarget | None: ...
    @abstractmethod
    def list_release_targets(self, project_id: str) -> tuple[ReleaseTarget, ...]: ...
    @abstractmethod
    def save_human_action(self, value: HumanActionRequest, audit: AuditEvent | None = None) -> None: ...
    @abstractmethod
    def get_human_action(self, human_action_id: str) -> HumanActionRequest | None: ...
    @abstractmethod
    def list_human_actions(self, project_id: str) -> tuple[HumanActionRequest, ...]: ...
    @abstractmethod
    def save_notification(self, value: NotificationEvent) -> None: ...
    @abstractmethod
    def get_notification(self, notification_id: str) -> NotificationEvent | None: ...
    @abstractmethod
    def list_notifications(self, project_id: str) -> tuple[NotificationEvent, ...]: ...
    @abstractmethod
    def append_notification_delivery_attempt(self, value: NotificationDeliveryAttempt) -> None: ...
    @abstractmethod
    def list_notification_delivery_attempts(self, project_id: str) -> tuple[NotificationDeliveryAttempt, ...]: ...
    @abstractmethod
    def apply_human_action_operational_transition(self, action: HumanActionRequest, project: Project, transition: ProjectOperationalTransition, audit: AuditEvent | None = None) -> None: ...
    @abstractmethod
    def save_approval(self, value: ApprovalRecord, audit: AuditEvent | None = None) -> None: ...
    @abstractmethod
    def get_approval(self, approval_id: str) -> ApprovalRecord | None: ...
    @abstractmethod
    def list_approvals(self, project_id: str) -> tuple[ApprovalRecord, ...]: ...
    @abstractmethod
    def save_runtime_idempotency(self, value: RuntimeIdempotencyRecord) -> None: ...
    @abstractmethod
    def get_runtime_idempotency(self, record_id: str) -> RuntimeIdempotencyRecord | None: ...
    @abstractmethod
    def list_runtime_idempotency(self, project_id: str) -> tuple[RuntimeIdempotencyRecord, ...]: ...
    @abstractmethod
    def append_policy_decision(self, value: PolicyDecision) -> None: ...
    @abstractmethod
    def list_policy_decisions(self, project_id: str) -> tuple[PolicyDecision, ...]: ...
    @abstractmethod
    def append_audit_event(self, value: AuditEvent) -> None: ...
    @abstractmethod
    def list_audit_events(self, project_id: str) -> tuple[AuditEvent, ...]: ...
    @abstractmethod
    def append_routing_record(self, value: RoutingRecord) -> None: ...
    @abstractmethod
    def list_routing_records(self, project_id: str) -> tuple[RoutingRecord, ...]: ...
    @abstractmethod
    def append_release_validation_record(self, value: ReleaseValidationRecord) -> None: ...
    @abstractmethod
    def list_release_validation_records(self, project_id: str) -> tuple[ReleaseValidationRecord, ...]: ...
