from __future__ import annotations

from pathlib import Path

from .contracts import AgentBlueprint, ScaffoldFile, ScaffoldValidationReport


class ScaffoldConflictError(RuntimeError):
    pass


class AgentScaffolder:
    REQUIRED_FILES = ("agent.py", "test_agent.py", "README.md")

    def render(self, blueprint: AgentBlueprint) -> tuple[ScaffoldFile, ...]:
        capability_ids = ", ".join(repr(item.capability_id) for item in blueprint.capabilities)
        agent_source = f'''from models.agent import AgentRunRequest, AgentRunResult\nfrom models.enums import ExecutionStatus\nfrom runtime.contracts import ExecutionControl\n\n\nclass {blueprint.class_name}:\n    """Generated K_Supervisor agent scaffold."""\n\n    def __call__(self, request: AgentRunRequest, control: ExecutionControl) -> AgentRunResult:\n        control.check_cancelled()\n        return AgentRunResult(\n            request_id=request.request_id,\n            project_id=request.project_id,\n            task_id=request.task_id,\n            workflow_run_id=request.workflow_run_id,\n            run_id=request.run_id,\n            agent_id=request.agent_id,\n            capability_id=request.capability_id,\n            capability_version=request.capability_version,\n            status=ExecutionStatus.SUCCEEDED,\n            output={{"implemented": False}},\n            warnings=("generated scaffold handler requires domain implementation",),\n        )\n'''
        test_source = f'''from agent import {blueprint.class_name}\n\n\ndef test_agent_scaffold_constructs():\n    assert {blueprint.class_name}() is not None\n'''
        readme = f'''# {blueprint.display_name}\n\nGenerated by K_Supervisor AgentFactory.\n\n- agent_id: `{blueprint.agent_id}`\n- agent_type: `{blueprint.agent_type}`\n- contract_version: `{blueprint.contract_version}`\n- capabilities: {capability_ids}\n\nImplement domain behavior in `agent.py`, keep the Agent Contract unchanged, then extend `test_agent.py`.\n'''
        return (
            ScaffoldFile(path="agent.py", content=agent_source),
            ScaffoldFile(path="test_agent.py", content=test_source),
            ScaffoldFile(path="README.md", content=readme),
        )

    def validate(self, files: tuple[ScaffoldFile, ...]) -> ScaffoldValidationReport:
        by_path = {item.path: item for item in files}
        errors: list[str] = []
        for required in self.REQUIRED_FILES:
            if required not in by_path:
                errors.append(f"missing required scaffold file: {required}")
        for item in files:
            if item.path.endswith(".py"):
                try:
                    compile(item.content, item.path, "exec")
                except SyntaxError as exc:
                    errors.append(f"{item.path}: {exc.msg}")
        return ScaffoldValidationReport(
            valid=not errors,
            checked_files=tuple(sorted(by_path)),
            errors=tuple(errors),
        )

    def write(self, root: str | Path, blueprint: AgentBlueprint) -> tuple[Path, ...]:
        root_path = Path(root)
        root_path.mkdir(parents=True, exist_ok=True)
        files = self.render(blueprint)
        report = self.validate(files)
        if not report.valid:
            raise ValueError("invalid generated scaffold: " + "; ".join(report.errors))

        written: list[Path] = []
        for item in files:
            target = root_path / item.path
            if target.exists():
                current = target.read_text(encoding="utf-8")
                if current != item.content:
                    raise ScaffoldConflictError(f"scaffold file conflict: {target}")
            else:
                target.write_text(item.content, encoding="utf-8")
            written.append(target)
        return tuple(written)
