from enum import StrEnum


class ProjectSpecStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ProjectLifecycleState(StrEnum):
    IDEA = "IDEA"
    ONBOARDING = "ONBOARDING"
    SPEC_REVIEW = "SPEC_REVIEW"
    APPROVED = "APPROVED"
    PROVISIONING = "PROVISIONING"
    BOOTSTRAPPED = "BOOTSTRAPPED"
    BUILDING = "BUILDING"
    VALIDATING = "VALIDATING"
    FIRST_WORKING = "FIRST_WORKING"
    RELEASE_PREPARATION = "RELEASE_PREPARATION"
    RELEASE_READY = "RELEASE_READY"
    MAINTENANCE = "MAINTENANCE"
    ARCHIVED = "ARCHIVED"
    TERMINATED = "TERMINATED"


class ProjectOperationalState(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    WAITING_FOR_OWNER = "WAITING_FOR_OWNER"
    WAITING_FOR_EXTERNAL = "WAITING_FOR_EXTERNAL"
    BLOCKED = "BLOCKED"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"


class ExecutionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"
    BLOCKED = "BLOCKED"


class HumanActionStatus(StrEnum):
    OPEN = "OPEN"
    NOTIFIED = "NOTIFIED"
    WAITING_FOR_OWNER = "WAITING_FOR_OWNER"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class NotificationChannel(StrEnum):
    EMAIL = "EMAIL"


class DeliveryStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class ReleaseStatus(StrEnum):
    DRAFT = "DRAFT"
    PREPARING = "PREPARING"
    READY = "READY"
    PUBLICATION_REQUIRED = "PUBLICATION_REQUIRED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    WITHDRAWN = "WITHDRAWN"
    SUPERSEDED = "SUPERSEDED"
